# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AndorPyQTUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 706)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.singleAqc_btn = QtWidgets.QPushButton(self.centralwidget)
        self.singleAqc_btn.setObjectName("singleAqc_btn")
        self.horizontalLayout.addWidget(self.singleAqc_btn)
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setEnabled(True)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout.addWidget(self.stop_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.average_lbl = QtWidgets.QLabel(self.centralwidget)
        self.average_lbl.setObjectName("average_lbl")
        self.horizontalLayout_8.addWidget(self.average_lbl)
        self.avg_ctrl = QtWidgets.QSpinBox(self.centralwidget)
        self.avg_ctrl.setMinimum(1)
        self.avg_ctrl.setProperty("value", 1)
        self.avg_ctrl.setObjectName("avg_ctrl")
        self.horizontalLayout_8.addWidget(self.avg_ctrl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.integrationtime_lbl = QtWidgets.QLabel(self.centralwidget)
        self.integrationtime_lbl.setObjectName("integrationtime_lbl")
        self.horizontalLayout_5.addWidget(self.integrationtime_lbl)
        self.integrationTime_ctrl = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.integrationTime_ctrl.setDecimals(3)
        self.integrationTime_ctrl.setMinimum(0.021)
        self.integrationTime_ctrl.setMaximum(1000.0)
        self.integrationTime_ctrl.setSingleStep(0.001)
        self.integrationTime_ctrl.setObjectName("integrationTime_ctrl")
        self.horizontalLayout_5.addWidget(self.integrationTime_ctrl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startCooling_btn = QtWidgets.QPushButton(self.centralwidget)
        self.startCooling_btn.setObjectName("startCooling_btn")
        self.horizontalLayout_3.addWidget(self.startCooling_btn)
        self.stopCooling_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stopCooling_btn.setObjectName("stopCooling_btn")
        self.horizontalLayout_3.addWidget(self.stopCooling_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.temperature_lbl = QtWidgets.QLabel(self.centralwidget)
        self.temperature_lbl.setObjectName("temperature_lbl")
        self.horizontalLayout_2.addWidget(self.temperature_lbl)
        self.temperature_ctrl = QtWidgets.QSpinBox(self.centralwidget)
        self.temperature_ctrl.setMinimum(-20)
        self.temperature_ctrl.setMaximum(25)
        self.temperature_ctrl.setProperty("value", 0)
        self.temperature_ctrl.setObjectName("temperature_ctrl")
        self.horizontalLayout_2.addWidget(self.temperature_ctrl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.temp_lbl = QtWidgets.QLabel(self.centralwidget)
        self.temp_lbl.setObjectName("temp_lbl")
        self.horizontalLayout_6.addWidget(self.temp_lbl)
        self.currentTemp_lbl = QtWidgets.QLabel(self.centralwidget)
        self.currentTemp_lbl.setText("")
        self.currentTemp_lbl.setObjectName("currentTemp_lbl")
        self.horizontalLayout_6.addWidget(self.currentTemp_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.drawLayout = QtWidgets.QVBoxLayout()
        self.drawLayout.setObjectName("drawLayout")
        self.horizontalLayout_10.addLayout(self.drawLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.errorcode_lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.errorcode_lbl.setFont(font)
        self.errorcode_lbl.setText("")
        self.errorcode_lbl.setObjectName("errorcode_lbl")
        self.horizontalLayout_9.addWidget(self.errorcode_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 532, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AndorPyQT"))
        self.start_btn.setText(_translate("MainWindow", "Start Aqcuiring"))
        self.singleAqc_btn.setText(_translate("MainWindow", "Single Aqcuisition"))
        self.stop_btn.setText(_translate("MainWindow", "Stop Aqcuiring"))
        self.average_lbl.setText(_translate("MainWindow", "Average:"))
        self.integrationtime_lbl.setText(_translate("MainWindow", "Integration time [s]:"))
        self.startCooling_btn.setText(_translate("MainWindow", "start cooling"))
        self.stopCooling_btn.setText(_translate("MainWindow", "stop cooling"))
        self.temperature_lbl.setText(_translate("MainWindow", "Temperature:"))
        self.temp_lbl.setText(_translate("MainWindow", "Current temperature [°C]:"))
        self.label_3.setText(_translate("MainWindow", "error code:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))

